# GitHub Workflow to mark a preflight check commit status as being done.
name: Complete Preflight Checks

on:
  workflow_dispatch:
    inputs:
      check_run_id:
        type: string
        required: true
      conclusion:
        type: choice
        required: true
        options:
        - failure
        - success
      output_json:
        type: string

permissions:
  checks: write

jobs:
  mark_preflight_done:
    runs-on: ubuntu-latest
    steps:
    - name: mark preflight check GitHub check run as complete
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        cat <<- "EOF" | gh api -X PATCH \
                          --input - \
                          repos/gruntwork-clients/"${{ github.event.repository.name }}"/check-runs/"${{ github.event.inputs.check_run_id }}"
        {"name": "Preflight checks", "status": "completed", "conclusion": "${{ github.event.inputs.conclusion }}", "output": ${{ github.event.inputs.output_json }}}
        EOF
