# GitHub Workflow to check for idleness in the progress on a Reference Architecture deployment.
# 
# NOTE:
# - If idleness is found, it creates a GitHub issue to notify contributors to promote further engagement on the deployment.
# - If no idleness is found or the deployment was completed, no action is taken. It is safe to leave the workflow in place forever.

name: Idleness Check Workflow
# This workflow runs once per week to determine if progress on the Ref Arch deployment has halted. 
# It notifies Gruntwork customers by creating a GitHub issue explaining how to get support from Gruntwork.

# Controls when the workflow will run
on:
  schedule:
    # Schedule to run 20 UTC (8PM)  every Monday. 
    - cron: '00 20 * * 1'

jobs:
  createIssue:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      # Get the latest commit timestamp from the GitHub workspace under all branches.
      - name: Get the latest commit timestamp
        run: | 
          echo "LAST_COMMIT_EPOCH=$(git log --all -1 --format=%ct)" >> $GITHUB_ENV
          echo "WEEK_AGO_EPOCH=$(date +"%s" -d "7 days ago" )" >> $GITHUB_ENV
          
      # Check whether there's an open support ticket
      - name: Check for pre-existing GitHub issue
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          # Grabbing an open issue that matches certain title format.
          OPEN_ISSUE="$(gh search issues --match title --state open \"Idle Reference Architecture\" | awk 'NR == 1')"
          echo "OPEN_ISSUE=$OPEN_ISSUE" >> $GITHUB_ENV
          
      # Check whether the deployment is completed or not using the .repo_token file          
      - name: Check if .repo_token file exists
        id: has_repo_token
        shell: bash
        run: |
          if [[ -f .repo_token ]]; then
            echo "HAS_REPO_TOKEN=true" >> $GITHUB_ENV
          else
            echo "HAS_REPO_TOKEN=false" >> $GITHUB_ENV
          fi
  
      # Find the list of contributors of the repository.
      - name: Find contributors
        env:           
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          # Grabbing the collaborators in this repository + formatting.
          COLLABORATORS="$(gh api -X GET repos/{owner}/{repo}/collaborators -f affiliation='direct' | jq '.[].login' | sed 's/"//g' | sed 's/[^ ]* */@&/g')"
          echo "COLLABORATORS=$COLLABORATORS" >> $GITHUB_ENV
 
      # Runs a single command using the runners shell
      - name: Create idleness GitHub issue and notify collaborators
        if: env.OPEN_ISSUE == null && env.HAS_REPO_TOKEN && env.LAST_COMMIT_EPOCH <= env.WEEK_AGO_EPOCH
        uses: actions-ecosystem/action-create-issue@v1
        with:
          github_token: ${{ github.token }}
          title: Idle Reference Architecture for longer than 7 days
          body: We’ve noticed that you haven’t made any commits to your Reference Architecture for longer than 7 days. We understand that sometimes other projects and problems need to take priority! If you need assistance in any way with keeping your Reference Architecture progress moving along, please reach out to us at support@gruntwork.io. ${{env.COLLABORATORS}}
          labels: support
